version: '2'
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'echoboomer/terraform']
    volumes:
      - '.:/plugin:ro'
  tests:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    volumes:
      - '.:/plugin'
