name: Terraform
description: Runs Terraform in your pipeline.
author: https://github.com/echoboomer
requirements:
  - docker
configuration:
  properties:
    apply:
      type: boolean
    apply_only:
      type: boolean
    apply_master:
      type: boolean
    image:
      type: string
    init_config:
      type: [string, array]
    no_validate:
      type: boolean
    skip_apply_no_diff:
      type: boolean
    use_workspaces:
      type: boolean
    version:
      type: string
    workspace:
      type: string
  required:
    - init_config
